---
- name: Show Information
  hosts: routers
  gather_facts: False
  tasks:
    - name: show IP Int Br
      ios_command:
        commands:
        - show ip int br
      register: results

    - name: show results
      debug: msg={{ results["stdout_lines"][0] }} 